### ISSUE TITLE
Any reason we don't use paramiko?

### ISSUE THREAD

**Issue by davidxia** [spotify/crtauth#25]
I've only briefly read a bit of paramiko but it looks pretty full-featured in talking to ssh-agent. Do we not use for any reason?

**Comment by nresare** [comment]
Well, I wrote the bare socket client before I had a look at paramiko, and when it was already written it seemed to me like switching to paramiko and it's 21k lines to avoid maintaining a handful of lines in ssh.py was a bad idea.

 `pip install paramiko` on my system here triggers installation of paramiko, pycrypto and ecdsa and pycrypto compiles some c extensions so you need to have a working c toolchain to install it.

**Comment by davidxia** [comment]
Ah I didn't know paramiko had a lot of dependencies. Makes sense to skip it
then.

On Wednesday, October 21, 2015, Noa Resare <notifications@github.com> wrote:

> Well, I wrote the bare socket client before I had a look at paramiko, and
> when it was already written it seemed to me like switching to paramiko and
> it's 21k lines to avoid maintaining a handful of lines in ssh.py was a bad
> idea.
>
> pip install paramiko on my system here triggers installation of paramiko,
> pycrypto and ecdsa and pycrypto compiles some c extensions so you need to
> have a working c toolchain to install it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/crtauth/issues/25#issuecomment-149895228>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by nresare** [comment]
I think it makes sense to keep the solution we have and if we end up wanting some more functionality or seeing a bug that is a bit of work to fix we could make the switch. We could always ask @lndbrg for help with paramiko if we need it (Olle in pipedream)

**Comment by lndbrg** [comment]
Yeah, don't switch to paramiko unless needed.

Even though we will remove a lot of dependencies in one of the upcoming releases (pycrypto and soon also ecdsa) to rely on https://cryptography.io/ instead, there are a bunch of edge cases that aren't handled all that well in paramiko.
